// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {model} from '../models';

export function Connect(arg1:string):Promise<void>;

export function ConsumeMessages(arg1:backend.ConsumeRequest):Promise<Array<model.Message>>;

export function ConsumeMessagesByTimestamp(arg1:backend.ConsumeRequest):Promise<Array<model.Message>>;

export function CreateConnection(arg1:model.Connection):Promise<model.Connection>;

export function CreateTopic(arg1:backend.CreateTopicRequest):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConsumerGroup(arg1:backend.DeleteConsumerGroupRequest):Promise<void>;

export function DeleteTopic(arg1:backend.DeleteTopicRequest):Promise<void>;

export function DeleteTopics(arg1:backend.DeleteTopicsRequest):Promise<Array<model.TopicDeleteResult>>;

export function DescribeCluster(arg1:string):Promise<model.ClusterHealth>;

export function DescribeGroup(arg1:string,arg2:string):Promise<model.GroupDetail>;

export function DescribeTopic(arg1:string,arg2:string):Promise<model.TopicDetail>;

export function Disconnect(arg1:string):Promise<void>;

export function GetConnection(arg1:string):Promise<model.Connection>;

export function GetPartitionLag(arg1:string,arg2:string,arg3:string):Promise<Record<number, number>>;

export function ListActiveConsumers(arg1:backend.ActiveMembersRequest):Promise<Array<model.ActiveConsumer>>;

export function ListActiveProducers(arg1:backend.ActiveMembersRequest):Promise<Array<model.ActiveProducer>>;

export function ListConnections():Promise<Array<model.Connection>>;

export function ListConsumerGroups(arg1:string):Promise<Array<model.ConsumerGroup>>;

export function ListTopics(arg1:string):Promise<Array<model.Topic>>;

export function ProduceMessage(arg1:backend.ProduceRequest):Promise<void>;

export function ProduceMessages(arg1:backend.BatchProduceRequest):Promise<Array<model.ProduceResult>>;

export function ResetConsumerGroupOffset(arg1:backend.ResetOffsetRequest):Promise<void>;

export function TestConnection(arg1:model.KafkaConfig):Promise<void>;
