// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {model} from '../models';
import {store} from '../models';

export function AlterTopicConfig(arg1:backend.AlterTopicConfigRequest):Promise<void>;

export function AlterTopicPartitions(arg1:backend.AlterTopicPartitionsRequest):Promise<void>;

export function ApplyUpdate(arg1:backend.ApplyUpdateRequest):Promise<void>;

export function CHExecute(arg1:backend.CHExecuteRequest):Promise<Array<model.CHStatementResult>>;

export function CHPageRows(arg1:backend.CHPageRowsRequest):Promise<model.CHPageRowsResult>;

export function CHPreviewCellUpdate(arg1:model.CHCellUpdateRequest):Promise<model.CHCellUpdatePreview>;

export function CHTruncateTable(arg1:backend.CHTruncateTableRequest):Promise<void>;

export function CHUpdateCell(arg1:model.CHCellUpdateRequest):Promise<void>;

export function CheckUpdate(arg1:backend.CheckUpdateRequest):Promise<backend.UpdateCheckResult>;

export function Connect(arg1:string):Promise<void>;

export function ConsumeMessages(arg1:backend.ConsumeRequest):Promise<Array<model.Message>>;

export function ConsumeMessagesByTimestamp(arg1:backend.ConsumeRequest):Promise<Array<model.Message>>;

export function CreateConnection(arg1:model.Connection):Promise<model.Connection>;

export function CreateTopic(arg1:backend.CreateTopicRequest):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConsumerGroup(arg1:backend.DeleteConsumerGroupRequest):Promise<void>;

export function DeleteEsTemplate(arg1:backend.EsDeleteTemplateRequest):Promise<void>;

export function DeleteQueryFile(arg1:backend.QueryFileDeleteRequest):Promise<void>;

export function DeleteSavedQuery(arg1:backend.DeleteSavedQueryRequest):Promise<void>;

export function DeleteTopic(arg1:backend.DeleteTopicRequest):Promise<void>;

export function DeleteTopics(arg1:backend.DeleteTopicsRequest):Promise<Array<model.TopicDeleteResult>>;

export function DescribeCluster(arg1:string):Promise<model.ClusterHealth>;

export function DescribeGroup(arg1:string,arg2:string):Promise<model.GroupDetail>;

export function DescribeTopic(arg1:string,arg2:string):Promise<model.TopicDetail>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:backend.DownloadUpdateRequest):Promise<void>;

export function ESDeleteByQuery(arg1:backend.EsDeleteByQueryRequest):Promise<number>;

export function ESDeleteDoc(arg1:backend.EsDeleteDocRequest):Promise<void>;

export function ESDsl(arg1:backend.EsDslRequest):Promise<model.EsDslResult>;

export function ESExecute(arg1:backend.EsExecuteRequest):Promise<Array<model.EsStatementResult>>;

export function ESGetDoc(arg1:backend.EsGetDocRequest):Promise<model.EsDoc>;

export function ESMapping(arg1:backend.EsMappingRequest):Promise<Array<model.EsColumn>>;

export function ESPageRows(arg1:backend.EsPageRowsRequest):Promise<model.EsPageRowsResult>;

export function ESPutDoc(arg1:backend.EsPutDocRequest):Promise<void>;

export function ESUpdateCell(arg1:backend.EsCellUpdateRequest):Promise<void>;

export function EsClusterStats(arg1:backend.EsClusterStatsRequest):Promise<model.EsClusterStats>;

export function EsCreateDoc(arg1:backend.EsCreateDocRequest):Promise<model.EsDoc>;

export function EsCreateIndex(arg1:backend.EsCreateIndexRequest):Promise<void>;

export function EsDeleteIndex(arg1:backend.EsDeleteIndexRequest):Promise<void>;

export function EsRefreshIndex(arg1:backend.EsRefreshIndexRequest):Promise<void>;

export function EsUpdateIndexSettings(arg1:backend.EsUpdateIndexSettingsRequest):Promise<void>;

export function GetConnection(arg1:string):Promise<model.Connection>;

export function GetEsTemplate(arg1:backend.EsGetTemplateRequest):Promise<model.EsTemplateContent>;

export function GetPartitionLag(arg1:string,arg2:string,arg3:string):Promise<Record<number, number>>;

export function GetTopicMessageCounts(arg1:string,arg2:Array<string>):Promise<Record<string, model.TopicMessageCounts>>;

export function ListActiveConsumers(arg1:backend.ActiveMembersRequest):Promise<Array<model.ActiveConsumer>>;

export function ListActiveProducers(arg1:backend.ActiveMembersRequest):Promise<Array<model.ActiveProducer>>;

export function ListAudit(arg1:number):Promise<Array<model.AuditEntry>>;

export function ListCHDatabases(arg1:string):Promise<Array<string>>;

export function ListCHTables(arg1:backend.CHTablesRequest):Promise<Array<model.CHTableInfo>>;

export function ListConnections():Promise<Array<model.Connection>>;

export function ListConsumerGroups(arg1:string):Promise<Array<model.ConsumerGroup>>;

export function ListDrivers():Promise<Array<backend.DriverInfo>>;

export function ListESIndices(arg1:string):Promise<Array<model.EsIndexInfo>>;

export function ListEsTemplates(arg1:string):Promise<Array<model.EsTemplateInfo>>;

export function ListMysqlDatabases(arg1:string):Promise<Array<string>>;

export function ListMysqlTables(arg1:backend.MysqlTablesRequest):Promise<Array<model.MysqlTableInfo>>;

export function ListPostgresDatabases(arg1:string):Promise<Array<string>>;

export function ListPostgresSchemas(arg1:backend.PostgresSchemasRequest):Promise<Array<string>>;

export function ListPostgresTables(arg1:backend.PostgresTablesRequest):Promise<Array<model.PostgresTableInfo>>;

export function ListQueryFiles(arg1:backend.QueryFileListRequest):Promise<Array<store.QueryFileInfo>>;

export function ListRedisDBs(arg1:string):Promise<Array<model.RedisDBInfo>>;

export function ListSavedQueries(arg1:backend.ListSavedQueriesRequest):Promise<Array<model.SavedQuery>>;

export function ListTopics(arg1:string):Promise<Array<model.Topic>>;

export function MysqlExecute(arg1:backend.MysqlExecuteRequest):Promise<Array<model.MysqlStatementResult>>;

export function MysqlPageRows(arg1:backend.MysqlPageRowsRequest):Promise<model.MysqlPageRowsResult>;

export function MysqlPreviewCellUpdate(arg1:model.MysqlCellUpdateRequest):Promise<model.MysqlCellUpdatePreview>;

export function MysqlTruncateTable(arg1:backend.MysqlTruncateTableRequest):Promise<void>;

export function MysqlUpdateCell(arg1:model.MysqlCellUpdateRequest):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PostgresExecute(arg1:backend.PostgresExecuteRequest):Promise<Array<model.PostgresStatementResult>>;

export function PostgresPageRows(arg1:backend.PostgresPageRowsRequest):Promise<model.PostgresPageRowsResult>;

export function PostgresPreviewCellUpdate(arg1:model.PostgresCellUpdateRequest):Promise<model.PostgresCellUpdatePreview>;

export function PostgresTruncateTable(arg1:backend.PostgresTruncateTableRequest):Promise<void>;

export function PostgresUpdateCell(arg1:model.PostgresCellUpdateRequest):Promise<void>;

export function PreviewResetOffset(arg1:backend.ResetOffsetRequest):Promise<Record<number, number>>;

export function ProduceMessage(arg1:backend.ProduceRequest):Promise<void>;

export function ProduceMessages(arg1:backend.BatchProduceRequest):Promise<Array<model.ProduceResult>>;

export function PutEsTemplate(arg1:backend.EsPutTemplateRequest):Promise<void>;

export function ReadQueryFile(arg1:backend.QueryFileReadRequest):Promise<backend.QueryFileContent>;

export function RedisDeleteKeys(arg1:backend.RedisDeleteKeysRequest):Promise<number>;

export function RedisFlushAll(arg1:backend.RedisFlushRequest):Promise<void>;

export function RedisFlushDB(arg1:backend.RedisFlushRequest):Promise<void>;

export function RedisGetKey(arg1:backend.RedisKeyRequest):Promise<model.RedisValue>;

export function RedisHashDeleteField(arg1:backend.RedisHashFieldRequest):Promise<void>;

export function RedisHashSetField(arg1:backend.RedisHashFieldRequest):Promise<void>;

export function RedisListDeleteIndex(arg1:backend.RedisListIndexRequest):Promise<void>;

export function RedisListPush(arg1:backend.RedisListPushRequest):Promise<void>;

export function RedisListSetIndex(arg1:backend.RedisListIndexRequest):Promise<void>;

export function RedisRenameKey(arg1:backend.RedisKeyRequest):Promise<void>;

export function RedisScan(arg1:backend.RedisScanRequest):Promise<backend.RedisScanResult>;

export function RedisServerInfo(arg1:string):Promise<model.RedisServerInfo>;

export function RedisSetAdd(arg1:backend.RedisSetMemberRequest):Promise<void>;

export function RedisSetRemove(arg1:backend.RedisSetMemberRequest):Promise<void>;

export function RedisSetString(arg1:backend.RedisSetStringRequest):Promise<void>;

export function RedisSetTTL(arg1:backend.RedisKeyRequest):Promise<void>;

export function RedisZSetAdd(arg1:backend.RedisZSetMemberRequest):Promise<void>;

export function RedisZSetRemove(arg1:backend.RedisZSetMemberRequest):Promise<void>;

export function ResetConsumerGroupOffset(arg1:backend.ResetOffsetRequest):Promise<void>;

export function SaveSavedQuery(arg1:backend.SaveSavedQueryRequest):Promise<model.SavedQuery>;

export function SaveTextFile(arg1:backend.SaveTextFileRequest):Promise<string>;

export function TestCHConnection(arg1:model.ClickHouseConfig):Promise<void>;

export function TestConnection(arg1:model.KafkaConfig):Promise<void>;

export function TestESConnection(arg1:model.EsConfig):Promise<void>;

export function TestMysqlConnection(arg1:model.MysqlConfig):Promise<void>;

export function TestPostgresConnection(arg1:model.PostgresConfig):Promise<void>;

export function TestRedisConnection(arg1:model.RedisConfig):Promise<void>;

export function UpdateConnection(arg1:backend.UpdateConnectionRequest):Promise<model.Connection>;

export function UpdateProgress():Promise<backend.UpdateProgressInfo>;

export function UpdateSavedQuery(arg1:backend.UpdateSavedQueryRequest):Promise<model.SavedQuery>;

export function WriteQueryFile(arg1:backend.QueryFileWriteRequest):Promise<void>;
