// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function ConsumeMessages(arg1) {
  return window['go']['backend']['App']['ConsumeMessages'](arg1);
}

export function ConsumeMessagesByTimestamp(arg1) {
  return window['go']['backend']['App']['ConsumeMessagesByTimestamp'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['backend']['App']['CreateConnection'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['backend']['App']['CreateTopic'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['backend']['App']['DeleteConnection'](arg1);
}

export function DeleteConsumerGroup(arg1) {
  return window['go']['backend']['App']['DeleteConsumerGroup'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['backend']['App']['DeleteTopic'](arg1);
}

export function DeleteTopics(arg1) {
  return window['go']['backend']['App']['DeleteTopics'](arg1);
}

export function DescribeCluster(arg1) {
  return window['go']['backend']['App']['DescribeCluster'](arg1);
}

export function DescribeGroup(arg1, arg2) {
  return window['go']['backend']['App']['DescribeGroup'](arg1, arg2);
}

export function DescribeTopic(arg1, arg2) {
  return window['go']['backend']['App']['DescribeTopic'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['backend']['App']['Disconnect'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['backend']['App']['GetConnection'](arg1);
}

export function GetPartitionLag(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetPartitionLag'](arg1, arg2, arg3);
}

export function ListActiveConsumers(arg1) {
  return window['go']['backend']['App']['ListActiveConsumers'](arg1);
}

export function ListActiveProducers(arg1) {
  return window['go']['backend']['App']['ListActiveProducers'](arg1);
}

export function ListConnections() {
  return window['go']['backend']['App']['ListConnections']();
}

export function ListConsumerGroups(arg1) {
  return window['go']['backend']['App']['ListConsumerGroups'](arg1);
}

export function ListTopics(arg1) {
  return window['go']['backend']['App']['ListTopics'](arg1);
}

export function ProduceMessage(arg1) {
  return window['go']['backend']['App']['ProduceMessage'](arg1);
}

export function ProduceMessages(arg1) {
  return window['go']['backend']['App']['ProduceMessages'](arg1);
}

export function ResetConsumerGroupOffset(arg1) {
  return window['go']['backend']['App']['ResetConsumerGroupOffset'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}
