// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterTopicConfig(arg1) {
  return window['go']['backend']['App']['AlterTopicConfig'](arg1);
}

export function AlterTopicPartitions(arg1) {
  return window['go']['backend']['App']['AlterTopicPartitions'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['backend']['App']['ApplyUpdate'](arg1);
}

export function CHExecute(arg1) {
  return window['go']['backend']['App']['CHExecute'](arg1);
}

export function CHPageRows(arg1) {
  return window['go']['backend']['App']['CHPageRows'](arg1);
}

export function CHPreviewCellUpdate(arg1) {
  return window['go']['backend']['App']['CHPreviewCellUpdate'](arg1);
}

export function CHTruncateTable(arg1) {
  return window['go']['backend']['App']['CHTruncateTable'](arg1);
}

export function CHUpdateCell(arg1) {
  return window['go']['backend']['App']['CHUpdateCell'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['backend']['App']['CheckUpdate'](arg1);
}

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function ConsumeMessages(arg1) {
  return window['go']['backend']['App']['ConsumeMessages'](arg1);
}

export function ConsumeMessagesByTimestamp(arg1) {
  return window['go']['backend']['App']['ConsumeMessagesByTimestamp'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['backend']['App']['CreateConnection'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['backend']['App']['CreateTopic'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['backend']['App']['DeleteConnection'](arg1);
}

export function DeleteConsumerGroup(arg1) {
  return window['go']['backend']['App']['DeleteConsumerGroup'](arg1);
}

export function DeleteQueryFile(arg1) {
  return window['go']['backend']['App']['DeleteQueryFile'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['backend']['App']['DeleteSavedQuery'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['backend']['App']['DeleteTopic'](arg1);
}

export function DeleteTopics(arg1) {
  return window['go']['backend']['App']['DeleteTopics'](arg1);
}

export function DescribeCluster(arg1) {
  return window['go']['backend']['App']['DescribeCluster'](arg1);
}

export function DescribeGroup(arg1, arg2) {
  return window['go']['backend']['App']['DescribeGroup'](arg1, arg2);
}

export function DescribeTopic(arg1, arg2) {
  return window['go']['backend']['App']['DescribeTopic'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['backend']['App']['Disconnect'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['backend']['App']['DownloadUpdate'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['backend']['App']['GetConnection'](arg1);
}

export function GetPartitionLag(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetPartitionLag'](arg1, arg2, arg3);
}

export function GetTopicMessageCounts(arg1, arg2) {
  return window['go']['backend']['App']['GetTopicMessageCounts'](arg1, arg2);
}

export function ListActiveConsumers(arg1) {
  return window['go']['backend']['App']['ListActiveConsumers'](arg1);
}

export function ListActiveProducers(arg1) {
  return window['go']['backend']['App']['ListActiveProducers'](arg1);
}

export function ListAudit(arg1) {
  return window['go']['backend']['App']['ListAudit'](arg1);
}

export function ListCHDatabases(arg1) {
  return window['go']['backend']['App']['ListCHDatabases'](arg1);
}

export function ListCHTables(arg1) {
  return window['go']['backend']['App']['ListCHTables'](arg1);
}

export function ListConnections() {
  return window['go']['backend']['App']['ListConnections']();
}

export function ListConsumerGroups(arg1) {
  return window['go']['backend']['App']['ListConsumerGroups'](arg1);
}

export function ListDrivers() {
  return window['go']['backend']['App']['ListDrivers']();
}

export function ListMysqlDatabases(arg1) {
  return window['go']['backend']['App']['ListMysqlDatabases'](arg1);
}

export function ListMysqlTables(arg1) {
  return window['go']['backend']['App']['ListMysqlTables'](arg1);
}

export function ListQueryFiles(arg1) {
  return window['go']['backend']['App']['ListQueryFiles'](arg1);
}

export function ListRedisDBs(arg1) {
  return window['go']['backend']['App']['ListRedisDBs'](arg1);
}

export function ListSavedQueries(arg1) {
  return window['go']['backend']['App']['ListSavedQueries'](arg1);
}

export function ListTopics(arg1) {
  return window['go']['backend']['App']['ListTopics'](arg1);
}

export function MysqlExecute(arg1) {
  return window['go']['backend']['App']['MysqlExecute'](arg1);
}

export function MysqlPageRows(arg1) {
  return window['go']['backend']['App']['MysqlPageRows'](arg1);
}

export function MysqlPreviewCellUpdate(arg1) {
  return window['go']['backend']['App']['MysqlPreviewCellUpdate'](arg1);
}

export function MysqlTruncateTable(arg1) {
  return window['go']['backend']['App']['MysqlTruncateTable'](arg1);
}

export function MysqlUpdateCell(arg1) {
  return window['go']['backend']['App']['MysqlUpdateCell'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['backend']['App']['OpenURL'](arg1);
}

export function PreviewResetOffset(arg1) {
  return window['go']['backend']['App']['PreviewResetOffset'](arg1);
}

export function ProduceMessage(arg1) {
  return window['go']['backend']['App']['ProduceMessage'](arg1);
}

export function ProduceMessages(arg1) {
  return window['go']['backend']['App']['ProduceMessages'](arg1);
}

export function ReadQueryFile(arg1) {
  return window['go']['backend']['App']['ReadQueryFile'](arg1);
}

export function RedisDeleteKeys(arg1) {
  return window['go']['backend']['App']['RedisDeleteKeys'](arg1);
}

export function RedisFlushAll(arg1) {
  return window['go']['backend']['App']['RedisFlushAll'](arg1);
}

export function RedisFlushDB(arg1) {
  return window['go']['backend']['App']['RedisFlushDB'](arg1);
}

export function RedisGetKey(arg1) {
  return window['go']['backend']['App']['RedisGetKey'](arg1);
}

export function RedisHashDeleteField(arg1) {
  return window['go']['backend']['App']['RedisHashDeleteField'](arg1);
}

export function RedisHashSetField(arg1) {
  return window['go']['backend']['App']['RedisHashSetField'](arg1);
}

export function RedisListDeleteIndex(arg1) {
  return window['go']['backend']['App']['RedisListDeleteIndex'](arg1);
}

export function RedisListPush(arg1) {
  return window['go']['backend']['App']['RedisListPush'](arg1);
}

export function RedisListSetIndex(arg1) {
  return window['go']['backend']['App']['RedisListSetIndex'](arg1);
}

export function RedisRenameKey(arg1) {
  return window['go']['backend']['App']['RedisRenameKey'](arg1);
}

export function RedisScan(arg1) {
  return window['go']['backend']['App']['RedisScan'](arg1);
}

export function RedisServerInfo(arg1) {
  return window['go']['backend']['App']['RedisServerInfo'](arg1);
}

export function RedisSetAdd(arg1) {
  return window['go']['backend']['App']['RedisSetAdd'](arg1);
}

export function RedisSetRemove(arg1) {
  return window['go']['backend']['App']['RedisSetRemove'](arg1);
}

export function RedisSetString(arg1) {
  return window['go']['backend']['App']['RedisSetString'](arg1);
}

export function RedisSetTTL(arg1) {
  return window['go']['backend']['App']['RedisSetTTL'](arg1);
}

export function RedisZSetAdd(arg1) {
  return window['go']['backend']['App']['RedisZSetAdd'](arg1);
}

export function RedisZSetRemove(arg1) {
  return window['go']['backend']['App']['RedisZSetRemove'](arg1);
}

export function ResetConsumerGroupOffset(arg1) {
  return window['go']['backend']['App']['ResetConsumerGroupOffset'](arg1);
}

export function SaveSavedQuery(arg1) {
  return window['go']['backend']['App']['SaveSavedQuery'](arg1);
}

export function SaveTextFile(arg1) {
  return window['go']['backend']['App']['SaveTextFile'](arg1);
}

export function TestCHConnection(arg1) {
  return window['go']['backend']['App']['TestCHConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}

export function TestMysqlConnection(arg1) {
  return window['go']['backend']['App']['TestMysqlConnection'](arg1);
}

export function TestRedisConnection(arg1) {
  return window['go']['backend']['App']['TestRedisConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['backend']['App']['UpdateConnection'](arg1);
}

export function UpdateProgress() {
  return window['go']['backend']['App']['UpdateProgress']();
}

export function UpdateSavedQuery(arg1) {
  return window['go']['backend']['App']['UpdateSavedQuery'](arg1);
}

export function WriteQueryFile(arg1) {
  return window['go']['backend']['App']['WriteQueryFile'](arg1);
}
