package store

import (
	"errors"
	"strings"
	"testing"
	"time"

	"dataBasePro/backend/internal/model"
)

func sampleSavedQuery(name, consoleType, connectionID string) *model.SavedQuery {
	return &model.SavedQuery{
		Name:         name,
		ConsoleType:  consoleType,
		ConnectionID: connectionID,
		Content:      "SELECT 1",
	}
}

func TestStoreSavedQueryCreateAssignsIDAndTimestamps(t *testing.T) {
	s := newTestStore(t)
	q := sampleSavedQuery("每日消费延迟", "kafka-sql", "conn-1")
	if err := s.CreateSavedQuery(q); err != nil {
		t.Fatalf("CreateSavedQuery failed: %v", err)
	}
	if q.ID == "" {
		t.Fatal("id must be generated by the store")
	}
	if q.CreatedAt == 0 || q.UpdatedAt == 0 {
		t.Fatal("timestamps must be set")
	}
	if q.CreatedAt != q.UpdatedAt {
		t.Fatalf("create must set identical timestamps, got %d/%d", q.CreatedAt, q.UpdatedAt)
	}
	got, err := s.GetSavedQuery(q.ID)
	if err != nil {
		t.Fatalf("GetSavedQuery failed: %v", err)
	}
	if got.Name != "每日消费延迟" || got.ConsoleType != "kafka-sql" || got.ConnectionID != "conn-1" {
		t.Fatalf("fields not round-tripped: %+v", got)
	}
	if got.Content != "SELECT 1" {
		t.Fatalf("content not round-tripped: %q", got.Content)
	}
	if got.CreatedAt != q.CreatedAt || got.UpdatedAt != q.UpdatedAt {
		t.Fatalf("timestamps not persisted: got %d/%d want %d/%d", got.CreatedAt, got.UpdatedAt, q.CreatedAt, q.UpdatedAt)
	}
}

func TestStoreSavedQueryCreateDuplicateName(t *testing.T) {
	s := newTestStore(t)
	first := sampleSavedQuery("同名", "kafka-sql", "conn-1")
	if err := s.CreateSavedQuery(first); err != nil {
		t.Fatalf("create first failed: %v", err)
	}
	// 同 (console_type, connection_id) 下重名必须报中文错误。
	dup := sampleSavedQuery("同名", "kafka-sql", "conn-1")
	err := s.CreateSavedQuery(dup)
	if err == nil {
		t.Fatal("duplicate name in the same scope must fail")
	}
	if !strings.Contains(err.Error(), "同名查询已存在") {
		t.Fatalf("expected Chinese duplicate error, got %q", err.Error())
	}
	if dup.ID != "" {
		t.Fatalf("failed create must not assign an id, got %q", dup.ID)
	}
	// 同名但不同连接:允许。
	if err := s.CreateSavedQuery(sampleSavedQuery("同名", "kafka-sql", "conn-2")); err != nil {
		t.Fatalf("same name on another connection must be allowed: %v", err)
	}
	// 同名但不同控制台:允许。
	if err := s.CreateSavedQuery(sampleSavedQuery("同名", "ch-sql", "conn-1")); err != nil {
		t.Fatalf("same name on another console must be allowed: %v", err)
	}
}

func TestStoreSavedQueryUpdateAppliesAndRefreshesUpdatedAt(t *testing.T) {
	s := newTestStore(t)
	q := sampleSavedQuery("原名", "kafka-sql", "conn-1")
	if err := s.CreateSavedQuery(q); err != nil {
		t.Fatalf("create failed: %v", err)
	}
	createdAt, updatedAt := q.CreatedAt, q.UpdatedAt
	time.Sleep(2 * time.Millisecond) // 保证 updated_at 单调递增(UnixMilli 粒度)
	q.Name = "新名"
	q.Content = "SELECT 2"
	if err := s.UpdateSavedQuery(q); err != nil {
		t.Fatalf("update failed: %v", err)
	}
	if q.CreatedAt != createdAt {
		t.Fatalf("created_at must not change on update: got %d want %d", q.CreatedAt, createdAt)
	}
	if q.UpdatedAt <= updatedAt {
		t.Fatalf("updated_at must be refreshed on update: got %d <= %d", q.UpdatedAt, updatedAt)
	}
	got, err := s.GetSavedQuery(q.ID)
	if err != nil {
		t.Fatalf("get after update failed: %v", err)
	}
	if got.Name != "新名" || got.Content != "SELECT 2" {
		t.Fatalf("update not applied: %+v", got)
	}
	if got.ConsoleType != "kafka-sql" || got.ConnectionID != "conn-1" {
		t.Fatalf("update must not touch console_type/connection_id: %+v", got)
	}
	if got.UpdatedAt != q.UpdatedAt {
		t.Fatalf("refreshed updated_at not persisted: got %d want %d", got.UpdatedAt, q.UpdatedAt)
	}
}

func TestStoreSavedQueryUpdateDuplicateNameExcludesSelf(t *testing.T) {
	s := newTestStore(t)
	a := sampleSavedQuery("甲", "kafka-sql", "conn-1")
	b := sampleSavedQuery("乙", "kafka-sql", "conn-1")
	for _, q := range []*model.SavedQuery{a, b} {
		if err := s.CreateSavedQuery(q); err != nil {
			t.Fatalf("create failed: %v", err)
		}
	}
	// 改成别人的名字:拒绝。
	a.Name = "乙"
	err := s.UpdateSavedQuery(a)
	if err == nil {
		t.Fatal("renaming onto another query's name must fail")
	}
	if !strings.Contains(err.Error(), "同名查询已存在") {
		t.Fatalf("expected Chinese duplicate error, got %q", err.Error())
	}
	// 名字保持不变(排除自身):允许。
	a.Name = "甲"
	if err := s.UpdateSavedQuery(a); err != nil {
		t.Fatalf("keeping one's own name must be allowed: %v", err)
	}
}

func TestStoreSavedQueryUpdateMissing(t *testing.T) {
	s := newTestStore(t)
	err := s.UpdateSavedQuery(&model.SavedQuery{
		ID:           "nope",
		Name:         "缺失",
		ConsoleType:  "kafka-sql",
		ConnectionID: "conn-1",
		Content:      "SELECT 1",
	})
	if !errors.Is(err, ErrNotFound) {
		t.Fatalf("updating a missing saved query must return ErrNotFound, got %v", err)
	}
}

func TestStoreSavedQueryDelete(t *testing.T) {
	s := newTestStore(t)
	q := sampleSavedQuery("待删", "kafka-sql", "conn-1")
	if err := s.CreateSavedQuery(q); err != nil {
		t.Fatalf("create failed: %v", err)
	}
	if err := s.DeleteSavedQuery(q.ID); err != nil {
		t.Fatalf("delete failed: %v", err)
	}
	if _, err := s.GetSavedQuery(q.ID); !errors.Is(err, ErrNotFound) {
		t.Fatalf("saved query must be gone after delete, got %v", err)
	}
}

func TestStoreSavedQueryDeleteMissing(t *testing.T) {
	s := newTestStore(t)
	if err := s.DeleteSavedQuery("nope"); !errors.Is(err, ErrNotFound) {
		t.Fatalf("deleting a missing saved query must return ErrNotFound, got %v", err)
	}
}

func TestStoreSavedQueryListFilterCombinations(t *testing.T) {
	s := newTestStore(t)
	qa := sampleSavedQuery("A", "kafka-sql", "conn-1")
	qb := sampleSavedQuery("B", "kafka-sql", "conn-2")
	qc := sampleSavedQuery("C", "ch-sql", "conn-1")
	for _, q := range []*model.SavedQuery{qa, qb, qc} {
		if err := s.CreateSavedQuery(q); err != nil {
			t.Fatalf("create %s failed: %v", q.Name, err)
		}
	}
	all, err := s.ListSavedQueries("", "")
	if err != nil {
		t.Fatalf("list all failed: %v", err)
	}
	if len(all) != 3 {
		t.Fatalf("expected 3 saved queries, got %d", len(all))
	}
	byConsole, err := s.ListSavedQueries("kafka-sql", "")
	if err != nil {
		t.Fatalf("list by console failed: %v", err)
	}
	if len(byConsole) != 2 {
		t.Fatalf("expected 2 kafka-sql queries, got %d", len(byConsole))
	}
	byConn, err := s.ListSavedQueries("", "conn-1")
	if err != nil {
		t.Fatalf("list by connection failed: %v", err)
	}
	if len(byConn) != 2 {
		t.Fatalf("expected 2 queries for conn-1, got %d", len(byConn))
	}
	both, err := s.ListSavedQueries("kafka-sql", "conn-1")
	if err != nil {
		t.Fatalf("list by console+connection failed: %v", err)
	}
	if len(both) != 1 || both[0].Name != "A" {
		t.Fatalf("expected only A for (kafka-sql, conn-1), got %+v", both)
	}
	none, err := s.ListSavedQueries("mysql-sql", "conn-9")
	if err != nil {
		t.Fatalf("list empty scope failed: %v", err)
	}
	if none == nil || len(none) != 0 {
		t.Fatalf("empty result must be a non-nil empty slice, got %+v", none)
	}
}

func TestStoreSavedQueryListOrdersByUpdatedAtDesc(t *testing.T) {
	s := newTestStore(t)
	q1 := sampleSavedQuery("最早", "kafka-sql", "conn-1")
	if err := s.CreateSavedQuery(q1); err != nil {
		t.Fatalf("create q1 failed: %v", err)
	}
	time.Sleep(2 * time.Millisecond)
	q2 := sampleSavedQuery("居中", "kafka-sql", "conn-1")
	if err := s.CreateSavedQuery(q2); err != nil {
		t.Fatalf("create q2 failed: %v", err)
	}
	time.Sleep(2 * time.Millisecond)
	q3 := sampleSavedQuery("最新", "kafka-sql", "conn-1")
	if err := s.CreateSavedQuery(q3); err != nil {
		t.Fatalf("create q3 failed: %v", err)
	}
	names := func(list []*model.SavedQuery) []string {
		out := make([]string, 0, len(list))
		for _, q := range list {
			out = append(out, q.Name)
		}
		return out
	}
	if got := names(mustListSavedQueries(t, s, "kafka-sql", "conn-1")); got[0] != "最新" || got[1] != "居中" || got[2] != "最早" {
		t.Fatalf("expected newest-first order, got %v", got)
	}
	// 更新最早的条目后,它应排到最前。
	time.Sleep(2 * time.Millisecond)
	q1.Content = "SELECT 42"
	if err := s.UpdateSavedQuery(q1); err != nil {
		t.Fatalf("update q1 failed: %v", err)
	}
	if got := names(mustListSavedQueries(t, s, "kafka-sql", "conn-1")); got[0] != "最早" {
		t.Fatalf("updated entry must sort first, got %v", got)
	}
}

func mustListSavedQueries(t *testing.T, s *Store, consoleType, connectionID string) []*model.SavedQuery {
	t.Helper()
	list, err := s.ListSavedQueries(consoleType, connectionID)
	if err != nil {
		t.Fatalf("ListSavedQueries failed: %v", err)
	}
	return list
}
